name: CI
on: push

jobs:
  flow:
    name: Build (Web)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown

      - name: Install cargo-geng
        run: |
          cargo install cargo-geng --git https://github.com/kuviman/geng
          cargo install wasm-bindgen-cli

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: geng
          args: build --release --target wasm32-unknown-unknown --index-file play.html

      - name: Deploy GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/geng

      - name: Upload itch.io (Web)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: tsunami-run
          ITCH_USER: kuviman
          PACKAGE: target/geng
